version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./src:/app/src
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
 